name: Mars cibuildwheel

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, aarch64]
        include:
          - os: windows-latest
            arch: AMD64
          - os: macOS-latest
            arch: universal2            

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1

      - name: Build wheels
        uses: joerick/cibuildwheel@v2.3.1
        env:
          CIBW_BEFORE_BUILD: pip install -r ci/requirements-wheel.txt
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: pp* *-musllinux* cp36-*
          
      - name: Build source
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
          python -m pip install numpy scipy cython
          python setup.py sdist --dist-dir=wheelhouse
      - name: Release to pypi
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          python -m pip install --upgrade twine
          twine upload wheelhouse/*
      - name: Upload artifacts to github
        uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse
